spring.application.name=user-service
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.datasource.url=jdbc:postgresql://localhost:5434/userdb
spring.datasource.username=user-server-db-user-123
spring.datasource.password=user-service-db-password-123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1